// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import Topbar from './topbar';
import Leftbar from './leftbar';
import Rightbar from './rightbar';
import './application.css';


function render() {
    return <div className="application-application-2">
        <div className="application-0">
            <div className="application-topbar_instance-4">
                <Topbar mode={this.props.state.mode} changeToDesign={this.props.changeToDesign} changeToCode={this.props.changeToCode} color={"#ffffff"} /> 
            </div>
        </div>
        <div className="application-1">
            <div className="application-leftbar_instance-1">
                <Leftbar leftMode={this.props.state.leftMode} changeLeftBar={this.props.changeLeftBar} /> 
            </div>
            <div className="application-right_instance-1">
                <Rightbar rightMode={this.props.state.rightMode} addBinding={this.props.addBinding} showBindings={this.props.state.binding} showEvents={this.props.state.event} showRepeat={this.props.state.repeat} showConditional={this.props.state.conditional} showLink={this.props.state.link} showCursor={this.props.state.cursor} addEvent={this.props.addEvent} addRepeat={this.props.addRepeat} addConditional={this.props.addConditional} addLink={this.props.addLink} addCursor={this.props.addCursor} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
