// Generated by https://pagedraw.io/pages/10090
import React from 'react';
import Header from './header';
import './component_1.css';


function render() {
    return <div className="component_1-component_1">
        <div className="component_1-0">
            <div className="component_1-header-5">
                <Header text={""} img_src={""} text2={""} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
