// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './dropdown1.css';


function render() {
    return <div className="dropdown1-dropdown1">
        <div className="dropdown1-0">
            <div className="dropdown1-dropdown_grande-5">
                Dropdown grande
            </div>
            <div className="dropdown1-dropdown_grande_com-1">
                {"Dropdown grande com divisórias"}
            </div>
            <div className="dropdown1-dropdown_pequeno-5">
                Dropdown pequeno
            </div>
        </div>
        <div className="dropdown1-1">
            <div className="dropdown1-1-0">
                <div className="dropdown1-1-0-0">
                    <div className="dropdown1-path-8">
                        <div className="dropdown1-1-0-0-0-0">
                            <div className="dropdown1-wrap-1">Wrap</div>
                        </div>
                        <div className="dropdown1-1-0-0-0-1">
                            <div className="dropdown1-create_component-1">
                                Create Component
                            </div>
                        </div>
                        <div className="dropdown1-1-0-0-0-2">
                            <div className="dropdown1-copy-1">Copy</div>
                        </div>
                        <div className="dropdown1-1-0-0-0-3">
                            <div className="dropdown1-path-7">
                                <div className="dropdown1-1-0-0-0-3-0-0">
                                    <div className="dropdown1-remove-1">Remove</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="dropdown1-path-1">
                <div className="dropdown1-1-1-0">
                    <div className="dropdown1-path-2">
                        <div className="dropdown1-1-1-0-0-0">
                            <div className="dropdown1-back_to_menu-1">
                                Back to menu
                            </div>
                        </div>
                    </div>
                </div>
                <div className="dropdown1-1-1-1">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7454343181116981-1531117407918-751FE29F-C053-49BF-B812-B6084A7B79F2.png" className="dropdown1-line-7" /> 
                </div>
                <div className="dropdown1-1-1-2">
                    <div className="dropdown1-sync_code-1">Sync code</div>
                </div>
                <div className="dropdown1-1-1-3">
                    <div className="dropdown1-update_from_sketch-1">
                        Update from Sketch
                    </div>
                </div>
                <div className="dropdown1-1-1-4">
                    <div className="dropdown1-manage_components-9">
                        Manage components
                    </div>
                </div>
                <div className="dropdown1-1-1-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8522796624997299-1531117407917-C6188034-B881-4961-A20A-B03A054E1A09.png" className="dropdown1-line-8" /> 
                </div>
                <div className="dropdown1-1-1-6">
                    <div className="dropdown1-design_options-3">
                        Design options
                    </div>
                </div>
                <div className="dropdown1-1-1-7">
                    <div className="dropdown1-code_options-1">
                        Code options
                    </div>
                </div>
                <div className="dropdown1-1-1-8">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1838728077351851-1531117407915-ED3E33AC-8C95-4227-877C-671BB9627D23.png" className="dropdown1-line-1" /> 
                </div>
                <div className="dropdown1-1-1-9">
                    <div className="dropdown1-help-1">Help</div>
                </div>
                <div className="dropdown1-1-1-10">
                    <div className="dropdown1-get_desktop_app-1">
                        Get desktop app
                    </div>
                </div>
            </div>
            <div className="dropdown1-1-2">
                <div className="dropdown1-1-2-0">
                    <div className="dropdown1-path-12">
                        <div className="dropdown1-1-2-0-0-0">
                            <div className="dropdown1-path-6">
                                <div className="dropdown1-1-2-0-0-0-0-0">
                                    <div className="dropdown1-wrap-3">Wrap</div>
                                </div>
                            </div>
                        </div>
                        <div className="dropdown1-1-2-0-0-1">
                            <div className="dropdown1-create_component-16">
                                Create Component
                            </div>
                        </div>
                        <div className="dropdown1-1-2-0-0-2">
                            <div className="dropdown1-copy-12">Copy</div>
                        </div>
                        <div className="dropdown1-1-2-0-0-3">
                            <div className="dropdown1-remove-4">Remove</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="dropdown1-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
