// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './dropdown2.css';


function render() {
    return <div className="dropdown2-dropdown2">
        <div className="dropdown2-0">
            <div className="dropdown2-menu_global-1">Menu global</div>
        </div>
        <div className="dropdown2-1">
            <div className="dropdown2-1-0">
                <div className="dropdown2-1-0-0">
                    <div className="dropdown2-path-4">
                        <div className="dropdown2-1-0-0-0-0">
                            <div className="dropdown2-back_to_menu-1">
                                Back to menu
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-1">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3069655770107886-1531117407905-27815DF9-C09D-49B6-B39A-E6D1D9BAE398.png" className="dropdown2-line-3" /> 
                        </div>
                        <div className="dropdown2-1-0-0-0-2">
                            <div className="dropdown2-sync_code-1">Sync code</div>
                        </div>
                        <div className="dropdown2-1-0-0-0-3">
                            <div className="dropdown2-update_from_sketch-2">
                                Update from Sketch
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-4">
                            <div className="dropdown2-manage_components-3">
                                Manage components
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-5">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7812898059363013-1531117407902-58F14A21-DFDD-480D-A9FF-11688A11E45E.png" className="dropdown2-line-7" /> 
                        </div>
                        <div className="dropdown2-1-0-0-0-6">
                            <div className="dropdown2-design_options-1">
                                Design options
                            </div>
                            <div className="dropdown2-1-0-0-0-6-1">
                                <div className="dropdown2-1-0-0-0-6-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1453670845268141-1531117407906-A3C713C7-8DFE-4C37-9252-8B9B655DF73B.png" className="dropdown2-path_1" /> 
                                </div>
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-7">
                            <div className="dropdown2-code_options-2">
                                Code options
                            </div>
                            <div className="dropdown2-1-0-0-0-7-1">
                                <div className="dropdown2-1-0-0-0-7-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1016294678156700-1531117407908-BB7B3215-44DC-4CD2-8252-3F6D0DD4348B.png" className="dropdown2-path_12" /> 
                                </div>
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-8">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3982797682324073-1531117407480-C509442A-78EE-49DB-BCD8-74CBD6523BBE.png" className="dropdown2-line-39" /> 
                        </div>
                        <div className="dropdown2-1-0-0-0-9">
                            <div className="dropdown2-help-2">Help</div>
                            <div className="dropdown2-1-0-0-0-9-1">
                                <div className="dropdown2-1-0-0-0-9-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4929886640193195-1531117407910-5A08DC72-B0A9-47DC-A643-9CF39EFD7101.png" className="dropdown2-_-4" /> 
                                </div>
                            </div>
                        </div>
                        <div className="dropdown2-1-0-0-0-10">
                            <div className="dropdown2-get_desktop_app-1">
                                Get desktop app
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="dropdown2-1-1">
                <div className="dropdown2-1-1-0">
                    <div className="dropdown2-path-3">
                        <div className="dropdown2-1-1-0-0-0">
                            <div className="dropdown2-rescale_doc-7">Rescale doc</div>
                        </div>
                        <div className="dropdown2-1-1-0-0-1">
                            <div className="dropdown2-manage_fonts-3">
                                Manage fonts
                            </div>
                        </div>
                    </div>
                </div>
                <div className="dropdown2-1-1-1">
                    <div className="dropdown2-path-1">
                        <div className="dropdown2-1-1-1-0-0">
                            <div className="dropdown2-language-8">Language</div>
                            <div className="dropdown2-1-1-1-0-0-1">
                                <div className="dropdown2-1-1-1-0-0-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1282458612739991-1531117407912-F78BC5EE-66AE-4B8D-BE59-18AF5073B4B4.png" className="dropdown2-path_12-1" /> 
                                </div>
                            </div>
                        </div>
                        <div className="dropdown2-1-1-1-0-1">
                            <div className="dropdown2-css-6">CSS</div>
                            <div className="dropdown2-1-1-1-0-1-1">
                                <div className="dropdown2-1-1-1-0-1-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1276027633601980-1531117407913-A209AAF6-D107-4AAF-8E03-4CAB52404C34.png" className="dropdown2-path_12_" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="dropdown2-1-1-2">
                    <div className="dropdown2-path-14">
                        <div className="dropdown2-1-1-2-0-0">
                            <div className="dropdown2-shortcuts-4">Shortcuts</div>
                        </div>
                        <div className="dropdown2-1-1-2-0-1">
                            <div className="dropdown2-documentation-9">
                                Documentation
                            </div>
                        </div>
                        <div className="dropdown2-1-1-2-0-2">
                            <div className="dropdown2-video_tutorials-2">
                                Video Tutorials
                            </div>
                        </div>
                        <div className="dropdown2-1-1-2-0-3">
                            <div className="dropdown2-realease_notes-1">
                                Realease notes
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="dropdown2-1-2">
                <div className="dropdown2-1-2-0">
                    <div className="dropdown2-path-18">
                        <div className="dropdown2-1-2-0-0-0">
                            <div className="dropdown2-jsx-4">JSX</div>
                        </div>
                        <div className="dropdown2-1-2-0-0-1">
                            <div className="dropdown2-cjsx-7">CJSX</div>
                        </div>
                        <div className="dropdown2-1-2-0-0-2">
                            <div className="dropdown2-tsx-1">TSX</div>
                        </div>
                    </div>
                </div>
                <div className="dropdown2-1-2-1">
                    <div className="dropdown2-path-2">
                        <div className="dropdown2-1-2-1-0-0">
                            <div className="dropdown2-inline_css-7">Inline CSS</div>
                        </div>
                        <div className="dropdown2-1-2-1-0-1">
                            <div className="dropdown2-separeted_css-1">
                                Separeted CSS
                            </div>
                        </div>
                        <div className="dropdown2-1-2-1-0-2">
                            <div className="dropdown2-styled_components-1">
                                Styled Components
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="dropdown2-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
