// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './dropdown_copy_2.css';


function render() {
    return <div className="dropdown_copy_2-dropdown_copy_2">
        <div className="dropdown_copy_2-0">
            <div className="dropdown_copy_2-path-1">
                <div className="dropdown_copy_2-0-0-0">
                    <div className="dropdown_copy_2-wrap-3">Wrap</div>
                </div>
                <div className="dropdown_copy_2-0-0-1">
                    <div className="dropdown_copy_2-create_component-2">
                        Create Component
                    </div>
                </div>
                <div className="dropdown_copy_2-0-0-2">
                    <div className="dropdown_copy_2-copy-1">Copy</div>
                </div>
                <div className="dropdown_copy_2-0-0-3">
                    <div className="dropdown_copy_2-path-5">
                        <div className="dropdown_copy_2-0-0-3-0-0">
                            <div className="dropdown_copy_2-remove-1">Remove</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
