// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './dropdown3.css';


function render() {
    return <div className="dropdown3-dropdown3">
        <div className="dropdown3-0">
            <div className="dropdown3-menu_help-8">Menu help</div>
        </div>
        <div className="dropdown3-1">
            <div className="dropdown3-path-1">
                <div className="dropdown3-1-0-0">
                    <div className="dropdown3-shortcuts-1">Shortcuts</div>
                </div>
                <div className="dropdown3-1-0-1">
                    <div className="dropdown3-documentation-1">
                        Documentation
                    </div>
                </div>
                <div className="dropdown3-1-0-2">
                    <div className="dropdown3-video_tutorials-6">
                        Video Tutorials
                    </div>
                </div>
                <div className="dropdown3-1-0-3">
                    <div className="dropdown3-realease_notes-5">
                        Realease notes
                    </div>
                </div>
            </div>
        </div>
        <div className="dropdown3-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
