// Generated by https://pagedraw.io/pages/10090
import React from 'react';
import './header.css';


function render() {
    return <div className="header-header-7">
        <div className="header-0">
            <div className="header-path-1">
                <div className="header-0-0-0">
                    <div className="header-0-0-0-0">
                        <div className="header-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4908325009644240-1525899494479-87E2E30F-5CCD-4507-B2EF-3A9C6C96886C.png" className="header-mobile_signal-4" /> 
                        </div>
                    </div>
                    <div className="header-carrier-9">
                        { this.props.text2 }
                    </div>
                    <div className="header-0-0-0-2">
                        <div className="header-0-0-0-2-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6263012412673585-1525899494478-0D75D458-42F7-48D5-BE08-12B215DA8C5C.png" className="header-wi-fi-6" /> 
                        </div>
                    </div>
                    <div className="header-time-1">{"9:41 AM"}</div>
                    <div className="header-battery_percetage-1">{"100%"}</div>
                    <div className="header-0-0-0-5">
                        <div className="header-0-0-0-5-0">
                            <div className="header-border-1">
                                <div className="header-0-0-0-5-0-0-0">
                                    <div className="header-border_subtraction-3">
                                        <div className="header-0-0-0-5-0-0-0-0-0">
                                            <div className="header-battery_level-4" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="header-0-0-0-6">
                        <div className="header-0-0-0-6-0">
                            <div className="header-cap-1" /> 
                        </div>
                    </div>
                </div>
                <div className="header-0-0-1">
                    <div className="header-toolbar_copy-1" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}}>
                        <div className="header-0-0-1-0-0">
                            <div className="header-name-2">{ this.props.text }</div>
                        </div>
                    </div>
                </div>
                <div className="header-0-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1782004534125778-1525899494480-3BC319CC-773D-457B-AEDD-76A4823394FA.png" className="header-line-1" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
