// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './input-label.css';


function render() {
    return <div className="input-label-input-label-1">
        <div className="input-label-0">
            <div className="input-label-path-7">
                <div className="input-label-0-0-0">
                    <div className="input-label-this_props_list-1">
                        this.props.list
                    </div>
                    <div className="input-label-0-0-0-1">
                        <div className="input-label-0-0-0-1-0">
                            <div className="input-label-list-4">LIST</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
