// Generated by https://pagedraw.io/pages/10201
import React from 'react';
import './lala.css';


function render() {
    return <div className="lala">
        { (this.props.mode === "design") ?
            <div className="lala-design-4">
                <div className="lala-0-0-0">
                    <div className="lala-line-5" /> 
                    <div className="lala-0-0-0-1">
                        <div className="lala-0-0-0-1-0">
                            <div className="lala-rectangle_4">
                                <div className="lala-0-0-0-1-0-0-0">
                                    <div className="lala-line_3" /> 
                                    <div className="lala-0-0-0-1-0-0-0-1">
                                        <div className="lala-0-0-0-1-0-0-0-1-0">
                                            <div className="lala-rectangle_5" /> 
                                        </div>
                                    </div>
                                    <div className="lala-0-0-0-1-0-0-0-2">
                                        <div className="lala-0-0-0-1-0-0-0-2-0">
                                            <div className="lala-0-0-0-1-0-0-0-2-0-0">
                                                <div className="lala-rectangle_5-0" /> 
                                                <div className="lala-line_3-6" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="lala-0-0-0-1-0-0-0-3">
                                        <div className="lala-0-0-0-1-0-0-0-3-0">
                                            <div className="lala-rectangle_5-1" /> 
                                        </div>
                                    </div>
                                    <div className="lala-line_3-0" /> 
                                    <div className="lala-0-0-0-1-0-0-0-5">
                                        <div className="lala-0-0-0-1-0-0-0-5-0">
                                            <div className="lala-line_4" /> 
                                        </div>
                                        <div className="lala-0-0-0-1-0-0-0-5-1">
                                            <div className="lala-rectangle_5-8" /> 
                                        </div>
                                    </div>
                                    <div className="lala-0-0-0-1-0-0-0-6">
                                        <div className="lala-0-0-0-1-0-0-0-6-0">
                                            <div className="lala-0-0-0-1-0-0-0-6-0-0">
                                                <div className="lala-rectangle_5-7" /> 
                                                <div className="lala-line_4-1" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="lala-0-0-0-1-0-0-0-7">
                                        <div className="lala-0-0-0-1-0-0-0-7-0">
                                            <div className="lala-rectangle_5-2" /> 
                                        </div>
                                        <div className="lala-0-0-0-1-0-0-0-7-1">
                                            <div className="lala-line_4-5" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="lala-0-0-0-1-1">
                            <div className="lala-line_2" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.mode === "code") ?
            <div className="lala-code-7">
                <div className="lala-1-0-0">
                    <div className="lala-line-6" /> 
                    <div className="lala-1-0-0-1">
                        <div className="lala-1-0-0-1-0">
                            <div className="lala-rectangle_4-2">
                                <div className="lala-1-0-0-1-0-0-0">
                                    <div className="lala-line_3-63" /> 
                                    <div className="lala-1-0-0-1-0-0-0-1">
                                        <div className="lala-1-0-0-1-0-0-0-1-0">
                                            <div className="lala-rectangle_5-6" /> 
                                        </div>
                                    </div>
                                    <div className="lala-1-0-0-1-0-0-0-2">
                                        <div className="lala-1-0-0-1-0-0-0-2-0">
                                            <div className="lala-1-0-0-1-0-0-0-2-0-0">
                                                <div className="lala-rectangle_5-3" /> 
                                                <div className="lala-line_3-7" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="lala-1-0-0-1-0-0-0-3">
                                        <div className="lala-1-0-0-1-0-0-0-3-0">
                                            <div className="lala-rectangle_5-83" /> 
                                        </div>
                                    </div>
                                    <div className="lala-line_3-01" /> 
                                    <div className="lala-1-0-0-1-0-0-0-5">
                                        <div className="lala-1-0-0-1-0-0-0-5-0">
                                            <div className="lala-line_4-58" /> 
                                        </div>
                                        <div className="lala-1-0-0-1-0-0-0-5-1">
                                            <div className="lala-rectangle_5-07" /> 
                                        </div>
                                    </div>
                                    <div className="lala-1-0-0-1-0-0-0-6">
                                        <div className="lala-1-0-0-1-0-0-0-6-0">
                                            <div className="lala-1-0-0-1-0-0-0-6-0-0">
                                                <div className="lala-rectangle_5-09" /> 
                                                <div className="lala-line_4-2" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="lala-1-0-0-1-0-0-0-7">
                                        <div className="lala-1-0-0-1-0-0-0-7-0">
                                            <div className="lala-rectangle_5-78" /> 
                                        </div>
                                        <div className="lala-1-0-0-1-0-0-0-7-1">
                                            <div className="lala-line_4-4" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="lala-1-0-0-1-1">
                            <div className="lala-line_2-1" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
