// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './leftbar.css';


function render() {
    return <div className="leftbar">
        { (this.props.leftMode === "code-left-bar1") ?
            <div className="leftbar-code-left-bar1">
                <div className="leftbar-0-0-0">
                    <div className="leftbar-path-15">
                        <div className="leftbar-0-0-0-0-0">
                            <div className="leftbar-components-1">COMPONENTS</div>
                        </div>
                        <div className="leftbar-0-0-0-0-1">
                            <div className="leftbar-0-0-0-0-1-0">
                                <div className="leftbar-0-0-0-0-1-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1244521460406351-1531117410057-D94920EB-3DA1-484F-A9EF-A26CFB5E355A.png" className="leftbar-code_icon-1" /> 
                                </div>
                            </div>
                            <div onClick={this.props.changeLeftBar.bind(this, "code-left-bar4")} className="leftbar-dropdown-1">
                                dropdown
                            </div>
                        </div>
                        <div className="leftbar-0-0-0-0-2">
                            <div className="leftbar-0-0-0-0-2-0">
                                <div className="leftbar-0-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1577933843740404-1531117410056-E736FF1F-D8CE-45FF-83C8-8F7C5162CBFB.png" className="leftbar-code_icon-15" /> 
                                </div>
                            </div>
                            <div className="leftbar-screen1">screen1</div>
                        </div>
                        <div className="leftbar-0-0-0-0-3">
                            <div className="leftbar-0-0-0-0-3-0">
                                <div className="leftbar-0-0-0-0-3-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1804745641614294-1531117410051-1D359FC5-F3E6-42A0-B2C1-D233C93642CF.png" className="leftbar-code_icon-18" /> 
                                </div>
                            </div>
                            <div onMouseEnter={this.props.changeLeftBar.bind(this, "code-left-bar2")} className="leftbar-screen2">
                                screen2
                            </div>
                        </div>
                        <div className="leftbar-0-0-0-0-4">
                            <div className="leftbar-path-17">
                                <div className="leftbar-0-0-0-0-4-0-0">
                                    <div className="leftbar-oval-1">
                                        <div className="leftbar-0-0-0-0-4-0-0-0-0">
                                            <div className="leftbar-1-2">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-8">
                                        <div className="leftbar-0-0-0-0-4-0-0-1-0">
                                            <div className="leftbar-2-6">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-0-0-0-0-4-0-1">
                                    <div className="leftbar-0-0-0-0-4-0-1-0">
                                        <div className="leftbar-0-0-0-0-4-0-1-0-0">
                                            <div className="leftbar-path-1" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-0-0-0-0-4-0-1-1">
                                        <div className="leftbar-0-0-0-0-4-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-1">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-0-0-0-0-4-0-2">
                                    <div className="leftbar-0-0-0-0-4-0-2-0">
                                        <div className="leftbar-0-0-0-0-4-0-2-0-0">
                                            <div className="leftbar-path-5" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-0-0-0-0-4-0-2-1">
                                        <div className="leftbar-0-0-0-0-4-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-1">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-0-0-0-0-4-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-0-0-0-0-5" /> 
                    </div>
                </div>
            </div>
        : null}
        { (this.props.leftMode === "code-left-bar3") ?
            <div className="leftbar-code-left-bar3">
                <div className="leftbar-1-0-0">
                    <div className="leftbar-path-7">
                        <div className="leftbar-1-0-0-0-0">
                            <div className="leftbar-components-17">COMPONENTS</div>
                        </div>
                        <div className="leftbar-1-0-0-0-1">
                            <div className="leftbar-1-0-0-0-1-0">
                                <div className="leftbar-1-0-0-0-1-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7843454050262109-1531117410018-D5AB2692-7B16-43A6-95F3-D616405C608C.png" className="leftbar-code_icon-7" /> 
                                </div>
                            </div>
                            <div className="leftbar-dropdown-12">dropdown</div>
                        </div>
                        <div className="leftbar-1-0-0-0-2">
                            <div className="leftbar-1-0-0-0-2-0">
                                <div className="leftbar-1-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9376273620389866-1531117410017-9AE59C9E-AAEF-4321-91E6-685AA20A6239.png" className="leftbar-code_icon-9" /> 
                                </div>
                            </div>
                            <div className="leftbar-screen1-1">screen1</div>
                        </div>
                        <div className="leftbar-1-0-0-0-3">
                            <div className="leftbar-1-0-0-0-3-0">
                                <div className="leftbar-1-0-0-0-3-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2138402929963822-1531117410016-A8514922-8BC8-4828-9405-3B9D252B12E0.png" className="leftbar-code_icon-2" /> 
                                </div>
                            </div>
                            <div className="leftbar-screen2-1">screen2</div>
                            <div className="leftbar-1-0-0-0-3-2">
                                <div className="leftbar-1-0-0-0-3-2-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6744465822878120-1531117410024-93CDC11F-348C-4E66-B81B-C7B6D9516C22.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar1")} className="leftbar-shape-6" /> 
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-1-0-0-0-4">
                            <div className="leftbar-1-0-0-0-4-0">
                                <div className="leftbar-1-0-0-0-4-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1719082019271298-1531117410023-7CC50FD8-7FF1-431E-81A4-CF6AEADAC803.png" className="leftbar-line_9" /> 
                                </div>
                            </div>
                            <div className="leftbar-1-0-0-0-4-1">
                                <div className="leftbar-1-0-0-0-4-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7691775925340187-1531117410020-C91A444E-94BB-4EAA-9E6C-0F7B8CC29DD9.png" className="leftbar-shape-7" /> 
                                </div>
                                <div className="leftbar-1-0-0-0-4-1-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1654012954311497-1531117410022-59346103-9B31-401B-8464-B52007027B1B.png" className="leftbar-path_3" /> 
                                </div>
                            </div>
                            <div className="leftbar-1-0-0-0-4-2">
                                <div className="leftbar-1-0-0-0-4-2-0">
                                    <div className="leftbar-this_props_color-6">
                                        this.props.color
                                    </div>
                                </div>
                                <div className="leftbar-1-0-0-0-4-2-1">
                                    <div className="leftbar-this_props_change_o-2">
                                        {"this.props.change (onClick) "}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-1-0-0-0-5">
                            <div className="leftbar-path-8">
                                <div className="leftbar-1-0-0-0-5-0-0">
                                    <div className="leftbar-oval-10">
                                        <div className="leftbar-1-0-0-0-5-0-0-0-0">
                                            <div className="leftbar-1-1">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-15">
                                        <div className="leftbar-1-0-0-0-5-0-0-1-0">
                                            <div className="leftbar-2-8">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-1-0-0-0-5-0-1">
                                    <div className="leftbar-1-0-0-0-5-0-1-0">
                                        <div className="leftbar-1-0-0-0-5-0-1-0-0">
                                            <div className="leftbar-path-4" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-1-0-0-0-5-0-1-1">
                                        <div className="leftbar-1-0-0-0-5-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-12">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-1-0-0-0-5-0-2">
                                    <div className="leftbar-1-0-0-0-5-0-2-0">
                                        <div className="leftbar-1-0-0-0-5-0-2-0-0">
                                            <div className="leftbar-path-12" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-1-0-0-0-5-0-2-1">
                                        <div className="leftbar-1-0-0-0-5-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-13">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-1-0-0-0-5-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2-1">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="leftbar-1-0-1" /> 
            </div>
        : null}
        { (this.props.leftMode === "code-left-bar6") ?
            <div className="leftbar-code-left-bar6">
                <div className="leftbar-2-0-0">
                    <div className="leftbar-path-57">
                        <div className="leftbar-2-0-0-0-0">
                            <div className="leftbar-2-0-0-0-0-0">
                                <div className="leftbar-2-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1128681167183917-1531117409657-22F7FEB9-0BD6-4EC7-99E0-AF647E780A48.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar1")} className="leftbar-path_6" /> 
                                </div>
                            </div>
                            <div className="leftbar-dropdown-4">DROPDOWN</div>
                        </div>
                        <div className="leftbar-2-0-0-0-1">
                            <div className="leftbar-2-0-0-0-1-0">
                                <div className="leftbar-2-0-0-0-1-0-0">
                                    <div className="leftbar-path-16" /> 
                                </div>
                            </div>
                            <div className="leftbar-square-5">square</div>
                        </div>
                        <div className="leftbar-2-0-0-0-2">
                            <div className="leftbar-2-0-0-0-2-0">
                                <div className="leftbar-2-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4196365807557505-1531117409658-F297F2E6-3272-4AE9-8DAB-277CAB04A574.png" className="leftbar-oval_2" /> 
                                </div>
                            </div>
                            <div className="leftbar-oval-17">oval</div>
                        </div>
                        <div className="leftbar-2-0-0-0-3">
                            <div className="leftbar-2-0-0-0-3-0">
                                <div className="leftbar-2-0-0-0-3-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1289498902359434-1531117409659-8E0C9C79-DE7F-4215-954E-AC75FB290704.png" className="leftbar-format-text-1" /> 
                                </div>
                            </div>
                            <div className="leftbar-text-5">text</div>
                            <div className="leftbar-2-0-0-0-3-2">
                                <div className="leftbar-2-0-0-0-3-2-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1036598699299873-1531117409660-47FAD8B7-ABE7-4D2C-9BE2-0BA74E20D72C.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar4")} className="leftbar-code-braces-1" /> 
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-2-0-0-0-4">
                            <div className="leftbar-2-0-0-0-4-0">
                                <div className="leftbar-2-0-0-0-4-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1602507794088446-1531117409664-94E82B1F-00D7-4027-A865-6C02E7E2E9E1.png" className="leftbar-line_9-1" /> 
                                </div>
                            </div>
                            <div className="leftbar-2-0-0-0-4-1">
                                <div className="leftbar-2-0-0-0-4-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7742506941077072-1531117409661-7295B364-685D-4818-8192-3406BD777A5E.png" className="leftbar-shape-77" /> 
                                </div>
                                <div className="leftbar-2-0-0-0-4-1-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1408892136563409-1531117409662-FBBC6120-11FA-4CF2-8E2B-8743ED620AF7.png" className="leftbar-path_3-1" /> 
                                </div>
                            </div>
                            <div className="leftbar-2-0-0-0-4-2">
                                <div className="leftbar-2-0-0-0-4-2-0">
                                    <div className="leftbar-this_props_color-5">
                                        this.props.color
                                    </div>
                                </div>
                                <div className="leftbar-2-0-0-0-4-2-1">
                                    <div className="leftbar-this_props_change_o-1">
                                        {"this.props.change (onClick) "}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-2-0-0-0-5">
                            <div className="leftbar-path-74">
                                <div className="leftbar-2-0-0-0-5-0-0">
                                    <div className="leftbar-oval-105">
                                        <div className="leftbar-2-0-0-0-5-0-0-0-0">
                                            <div className="leftbar-1-7">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-5">
                                        <div className="leftbar-2-0-0-0-5-0-0-1-0">
                                            <div className="leftbar-2-1">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-2-0-0-0-5-0-1">
                                    <div className="leftbar-2-0-0-0-5-0-1-0">
                                        <div className="leftbar-2-0-0-0-5-0-1-0-0">
                                            <div className="leftbar-path-2" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-2-0-0-0-5-0-1-1">
                                        <div className="leftbar-2-0-0-0-5-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-17">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-2-0-0-0-5-0-2">
                                    <div className="leftbar-2-0-0-0-5-0-2-0">
                                        <div className="leftbar-2-0-0-0-5-0-2-0-0">
                                            <div className="leftbar-path-169" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-2-0-0-0-5-0-2-1">
                                        <div className="leftbar-2-0-0-0-5-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-10">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-2-0-0-0-5-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2-13">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="leftbar-2-0-1" /> 
            </div>
        : null}
        { (this.props.leftMode === "code-left-bar5") ?
            <div className="leftbar-code-left-bar5">
                <div className="leftbar-3-0-0">
                    <div className="leftbar-path-43">
                        <div className="leftbar-3-0-0-0-0">
                            <div className="leftbar-3-0-0-0-0-0">
                                <div className="leftbar-3-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4223311821406457-1531117409670-E744A4B8-AC53-40AF-B044-9BF7017720FF.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar1")} className="leftbar-path_6-4" /> 
                                </div>
                            </div>
                            <div className="leftbar-dropdown-11">DROPDOWN</div>
                        </div>
                        <div className="leftbar-3-0-0-0-1">
                            <div className="leftbar-3-0-0-0-1-0">
                                <div className="leftbar-3-0-0-0-1-0-0">
                                    <div className="leftbar-path-54" /> 
                                </div>
                            </div>
                            <div className="leftbar-square-7">square</div>
                        </div>
                        <div className="leftbar-3-0-0-0-2">
                            <div className="leftbar-3-0-0-0-2-0">
                                <div className="leftbar-3-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2654509806506008-1531117409669-75F967B6-E0AA-4D55-85D7-C9FF36983AAA.png" className="leftbar-oval_2-2" /> 
                                </div>
                            </div>
                            <div className="leftbar-oval-18">oval</div>
                        </div>
                        <div className="leftbar-3-0-0-0-3">
                            <div className="leftbar-rectangle_1">
                                <div className="leftbar-3-0-0-0-3-0-0">
                                    <div className="leftbar-3-0-0-0-3-0-0-0">
                                        <div className="leftbar-3-0-0-0-3-0-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3058726491192111-1531117409668-1657EF10-0C27-484B-AC84-9F45D31E0202.png" className="leftbar-format-text-3" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-text-4">text</div>
                                    <div className="leftbar-3-0-0-0-3-0-0-2">
                                        <div className="leftbar-3-0-0-0-3-0-0-2-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8568392765438631-1531117409667-072C1C15-2CF6-4FA2-87E7-DFCF0671203C.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar6")} className="leftbar-code-braces-8" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-3-0-0-0-4">
                            <div className="leftbar-path-167">
                                <div className="leftbar-3-0-0-0-4-0-0">
                                    <div className="leftbar-oval-182">
                                        <div className="leftbar-3-0-0-0-4-0-0-0-0">
                                            <div className="leftbar-1-4">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-9">
                                        <div className="leftbar-3-0-0-0-4-0-0-1-0">
                                            <div className="leftbar-2-17">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-3-0-0-0-4-0-1">
                                    <div className="leftbar-3-0-0-0-4-0-1-0">
                                        <div className="leftbar-3-0-0-0-4-0-1-0-0">
                                            <div className="leftbar-path-29" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-3-0-0-0-4-0-1-1">
                                        <div className="leftbar-3-0-0-0-4-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-15">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-3-0-0-0-4-0-2">
                                    <div className="leftbar-3-0-0-0-4-0-2-0">
                                        <div className="leftbar-3-0-0-0-4-0-2-0-0">
                                            <div className="leftbar-path-163" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-3-0-0-0-4-0-2-1">
                                        <div className="leftbar-3-0-0-0-4-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-139">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-3-0-0-0-4-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2-7">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="leftbar-3-0-1" /> 
            </div>
        : null}
        { (this.props.leftMode === "code-left-bar2") ?
            <div className="leftbar-code-left-bar2">
                <div className="leftbar-4-0-0">
                    <div className="leftbar-path-9">
                        <div className="leftbar-4-0-0-0-0">
                            <div className="leftbar-components-13">COMPONENTS</div>
                        </div>
                        <div className="leftbar-4-0-0-0-1">
                            <div className="leftbar-4-0-0-0-1-0">
                                <div className="leftbar-4-0-0-0-1-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9784915694959676-1531117410041-AB9141A2-93CB-44FB-B290-DC5E9869E0E8.png" className="leftbar-code_icon-97" /> 
                                </div>
                            </div>
                            <div className="leftbar-dropdown-44">dropdown</div>
                        </div>
                        <div className="leftbar-4-0-0-0-2">
                            <div className="leftbar-4-0-0-0-2-0">
                                <div className="leftbar-4-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1272239742809292-1531117410040-DA34601F-0FB1-4469-8C52-8DD699B6B698.png" className="leftbar-code_icon-12" /> 
                                </div>
                            </div>
                            <div className="leftbar-screen1-7">screen1</div>
                        </div>
                        <div className="leftbar-4-0-0-0-3">
                            <div className="leftbar-4-0-0-0-3-0">
                                <div className="leftbar-4-0-0-0-3-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1032133196508821-1531117410038-5972F434-6F15-429F-BFDC-BB04AF0A6C26.png" className="leftbar-code_icon-10" /> 
                                </div>
                            </div>
                            <div className="leftbar-screen2-17">screen2</div>
                            <div className="leftbar-4-0-0-0-3-2">
                                <div className="leftbar-4-0-0-0-3-2-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4409612114609717-1531117410043-D13D399D-EAE6-47DD-9B94-FE54E4D53A4E.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar3")} className="leftbar-shape-4" /> 
                                </div>
                            </div>
                        </div>
                        <div className="leftbar-4-0-0-0-4">
                            <div className="leftbar-path-174">
                                <div className="leftbar-4-0-0-0-4-0-0">
                                    <div className="leftbar-oval-12">
                                        <div className="leftbar-4-0-0-0-4-0-0-0-0">
                                            <div className="leftbar-1-8">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-127">
                                        <div className="leftbar-4-0-0-0-4-0-0-1-0">
                                            <div className="leftbar-2-15">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-4-0-0-0-4-0-1">
                                    <div className="leftbar-4-0-0-0-4-0-1-0">
                                        <div className="leftbar-4-0-0-0-4-0-1-0-0">
                                            <div className="leftbar-path-162" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-4-0-0-0-4-0-1-1">
                                        <div className="leftbar-4-0-0-0-4-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-5">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-4-0-0-0-4-0-2">
                                    <div className="leftbar-4-0-0-0-4-0-2-0">
                                        <div className="leftbar-4-0-0-0-4-0-2-0-0">
                                            <div className="leftbar-path-10" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-4-0-0-0-4-0-2-1">
                                        <div className="leftbar-4-0-0-0-4-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-17">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-4-0-0-0-4-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2-5">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="leftbar-4-0-1" /> 
            </div>
        : null}
        { (this.props.leftMode === "code-left-bar4") ?
            <div className="leftbar-code-left-bar4">
                <div className="leftbar-5-0-0">
                    <div className="leftbar-path-745">
                        <div className="leftbar-5-0-0-0-0">
                            <div className="leftbar-5-0-0-0-0-0">
                                <div className="leftbar-5-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3648213390459264-1531117409822-028658B6-2B3B-491E-9A2E-86CBEACCC629.png" onClick={this.props.changeLeftBar.bind(this, "code-left-bar1")} className="leftbar-path_6-3" /> 
                                </div>
                            </div>
                            <div className="leftbar-dropdown-116">DROPDOWN</div>
                        </div>
                        <div className="leftbar-5-0-0-0-1">
                            <div className="leftbar-5-0-0-0-1-0">
                                <div className="leftbar-5-0-0-0-1-0-0">
                                    <div className="leftbar-path-13" /> 
                                </div>
                            </div>
                            <div className="leftbar-square-73">square</div>
                        </div>
                        <div className="leftbar-5-0-0-0-2">
                            <div className="leftbar-5-0-0-0-2-0">
                                <div className="leftbar-5-0-0-0-2-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2090835882728644-1531117409821-3D9F7722-8B9E-4463-9B6D-93B2DAB1DFDF.png" className="leftbar-oval_2-20" /> 
                                </div>
                            </div>
                            <div className="leftbar-oval-14">oval</div>
                        </div>
                        <div className="leftbar-5-0-0-0-3">
                            <div className="leftbar-5-0-0-0-3-0">
                                <div className="leftbar-5-0-0-0-3-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1839128590954954-1531117409820-3F734A78-8E3F-44C1-B194-8E037ACC51B1.png" className="leftbar-format-text-18" /> 
                                </div>
                            </div>
                            <div onMouseEnter={this.props.changeLeftBar.bind(this, "code-left-bar5")} className="leftbar-text-1">
                                text
                            </div>
                        </div>
                        <div className="leftbar-5-0-0-0-4">
                            <div className="leftbar-path-173">
                                <div className="leftbar-5-0-0-0-4-0-0">
                                    <div className="leftbar-oval-2">
                                        <div className="leftbar-5-0-0-0-4-0-0-0-0">
                                            <div className="leftbar-1-3">1</div>
                                        </div>
                                    </div>
                                    <div className="leftbar-oval-91">
                                        <div className="leftbar-5-0-0-0-4-0-0-1-0">
                                            <div className="leftbar-2-13">2</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-5-0-0-0-4-0-1">
                                    <div className="leftbar-5-0-0-0-4-0-1-0">
                                        <div className="leftbar-5-0-0-0-4-0-1-0-0">
                                            <div className="leftbar-path-435" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-5-0-0-0-4-0-1-1">
                                        <div className="leftbar-5-0-0-0-4-0-1-1-0">
                                            <div className="leftbar-main_-_empty_overrid-18">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="leftbar-5-0-0-0-4-0-2">
                                    <div className="leftbar-5-0-0-0-4-0-2-0">
                                        <div className="leftbar-5-0-0-0-4-0-2-0-0">
                                            <div className="leftbar-path-25" /> 
                                        </div>
                                    </div>
                                    <div className="leftbar-5-0-0-0-4-0-2-1">
                                        <div className="leftbar-5-0-0-0-4-0-2-1-0">
                                            <div className="leftbar-main_-_empty_overrid_copy-9">
                                                main - Empty override code
                                            </div>
                                        </div>
                                        <div className="leftbar-5-0-0-0-4-0-2-1-1">
                                            <div className="leftbar-main_-_empty_overrid_copy_2-15">
                                                main - Empty override code
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="leftbar-5-0-1" /> 
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
