// Generated by https://pagedraw.io/pages/10090
import React from 'react';
import Component_1 from './component_1';
import './main.css';


function render() {
    return <div className="main-main-1">
        <div className="main-0">
            <div className="main-component_1"><Component_1 /> </div>
        </div>
        <div className="main-1">
            <div className="main-1-0">
                <div className="main-1-0-0">
                    <div className="main-1-0-0-0">
                        <div onClick={this.props.handleClick} className="main-local_change-1">
                            <div>LOCAL</div>
                            <div>CHANGE </div>
                        </div>
                        <div onClick={this.props.handleClick} className="main-global_impact-1" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="main-2">
            <div className="main-path-4">
                <div className="main-2-0-0">
                    <div className="main-2-0-0-0">
                        <div className="main-2-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7611303836045407-1525899494132-3C93E937-2B6B-449B-BB8B-59390ED4C7E7.png" className="main-ios-location_copy-7" /> 
                        </div>
                    </div>
                    <div className="main-text_copy-1">Location</div>
                    <div className="main-2-0-0-2" /> 
                </div>
            </div>
        </div>
        <div className="main-3">
            <div className="main-oval-1">
                <div className="main-3-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2161158535867965-1525899494134-A2E03FAA-4BD8-42AB-A90B-92B1B78B48C1.png" className="main-group-2" /> 
                </div>
                <div className="main-3-0-1">
                    <div className="main-text_copy_2">Science</div>
                </div>
            </div>
            <div onClick={this.props.handleClick} className="main-oval_copy-7">
                <div className="main-3-1-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1623182355304640-1525899494135-AB55C03C-02A4-49F9-9984-8A84C2B7EAB4.png" className="main-group-1" /> 
                </div>
                <div className="main-3-1-1">
                    <div className="main-text_copy_4">Animals</div>
                </div>
            </div>
            <div className="main-oval_copy_2">
                <div className="main-3-2-0">
                    <div className="main-group-17" /> 
                </div>
                <div className="main-3-2-1">
                    <div className="main-text_copy_3">Community</div>
                </div>
            </div>
            <div className="main-oval_copy_3">
                <div className="main-3-3-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1115908418414485-1525899494460-C6BAE265-A33D-4091-8EBA-0EEAD5E9FCDE.png" className="main-shape-1" /> 
                </div>
                <div className="main-3-3-1">
                    <div className="main-text_copy_5">Sports</div>
                </div>
            </div>
        </div>
        <div className="main-4">
            <div className="main-4-0">
                <div className="main-4-0-0">
                    <div className="main-4-0-0-0">
                        <div className="main-path-1">
                            <div className="main-4-0-0-0-0-0">
                                <div className="main-name-3">Companies</div>
                            </div>
                        </div>
                        <div className="main-path-2">
                            <div className="main-4-0-0-0-1-0">
                                <div className="main-name-1">{ this.props.text4 }</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="main-5" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
