// Generated by https://pagedraw.io/pages/10090
import React from 'react';
import './opportunity_thumb.css';


function render() {
    return <div className="opportunity_thumb-opportunity_thumb-1">
        <div className="opportunity_thumb-0">
            <div className="opportunity_thumb-path-4">
                <div className="opportunity_thumb-0-0-0">
                    <div className="opportunity_thumb-name-4">
                        Clothes to the poor
                    </div>
                </div>
                <div className="opportunity_thumb-0-0-1">
                    <div className="opportunity_thumb-0-0-1-0">
                        <div className="opportunity_thumb-0-0-1-0-0">
                            <div className="opportunity_thumb-status-8">
                                GOOD CLOTHES
                            </div>
                        </div>
                        <div className="opportunity_thumb-0-0-1-0-1">
                            <div className="opportunity_thumb-status_copy-1">
                                We need people to help us giving clothes to people in south San Francisco
                            </div>
                        </div>
                    </div>
                    <div className="opportunity_thumb-0-0-1-1">
                        <div className="opportunity_thumb-0-0-1-1-0">
                            <div className="opportunity_thumb-name-1">View</div>
                        </div>
                    </div>
                </div>
                <div className="opportunity_thumb-0-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5259397224989921-1525899493451-7F56395D-AC69-4937-835B-8D5EBCEE055F.png" className="opportunity_thumb-line_copy_7" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
