// Generated by https://pagedraw.io/pages/10201
import React from 'react';
import './outronome.css';


function render() {
    return <div className="outronome-outronome-4">
        <div className="outronome-0">
            { this.props.show ?
                <div className="outronome-rectangle_6">
                    <div className="outronome-0-0-0-0">
                        <div className="outronome-text-8">{ this.props.text }</div>
                    </div>
                </div>
            : null}
        </div>
        <div className="outronome-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
