// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './responsiveness1.css';


function render() {
    return <div className="responsiveness1-responsiveness1">
        <div className="responsiveness1-0">
            <div className="responsiveness1-path-8">
                <div className="responsiveness1-0-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5534811011196401-1531117410375-A620CE14-A36B-46AB-963F-FFEE61AFDADC.png" className="responsiveness1-shape-5" /> 
                </div>
                <div className="responsiveness1-0-0-1">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1429368454000207-1531117410374-F12F5C4C-2F73-4A9D-83BF-B70522250A4A.png" className="responsiveness1-path_3" /> 
                </div>
                <div className="responsiveness1-0-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4873243626272430-1531117410373-6D1316DF-0D56-4331-879A-7BCE2F4A7209.png" className="responsiveness1-repeat-4" /> 
                </div>
                <div className="responsiveness1-0-0-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4947170392849922-1531117410372-695DE70B-B517-4B32-91EB-0220126CA086.png" className="responsiveness1-optional-4" /> 
                </div>
                <div className="responsiveness1-0-0-4">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2700749648674304-1531117410371-4810DA6E-040D-4526-82D1-80B3C365BC65.png" className="responsiveness1-link_round-_1" /> 
                </div>
                <div className="responsiveness1-0-0-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4194286487952633-1531117410370-FAE826C6-BE4E-4BAC-828F-32C3B289D410.png" className="responsiveness1-shape-4" /> 
                </div>
            </div>
            <div className="responsiveness1-path-18">
                <div className="responsiveness1-0-1-0">
                    <div className="responsiveness1-path-7">
                        <div className="responsiveness1-0-1-0-0-0">
                            <div className="responsiveness1-alignment-1">
                                ALIGNMENT
                            </div>
                        </div>
                        <div className="responsiveness1-0-1-0-0-1">
                            <div className="responsiveness1-path-6">
                                <div className="responsiveness1-0-1-0-0-1-0-0">
                                    <div className="responsiveness1-fixed_left-6">
                                        Fixed left
                                    </div>
                                    <div className="responsiveness1-0-1-0-0-1-0-0-1">
                                        <div className="responsiveness1-0-1-0-0-1-0-0-1-0">
                                            <div className="responsiveness1-horizontal-8">
                                                HORIZONTAL
                                            </div>
                                        </div>
                                    </div>
                                    <div className="responsiveness1-0-1-0-0-1-0-0-2">
                                        <div className="responsiveness1-0-1-0-0-1-0-0-2-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1679482625153936-1531117410376-6FE7F5BE-AB5A-4390-8F83-31F3073B988D.png" className="responsiveness1-path_9" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="responsiveness1-0-1-0-0-2">
                            <div className="responsiveness1-path-1">
                                <div className="responsiveness1-0-1-0-0-2-0-0">
                                    <div className="responsiveness1-fixed_top-8">
                                        Fixed top
                                    </div>
                                    <div className="responsiveness1-0-1-0-0-2-0-0-1">
                                        <div className="responsiveness1-0-1-0-0-2-0-0-1-0">
                                            <div className="responsiveness1-vertical-1">VERTICAL</div>
                                        </div>
                                    </div>
                                    <div className="responsiveness1-0-1-0-0-2-0-0-2">
                                        <div className="responsiveness1-0-1-0-0-2-0-0-2-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1510863638206598-1531117410376-F968C5AC-B081-451E-B07C-703111053BB6.png" className="responsiveness1-path_9-1" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="responsiveness1-0-1-1">
                    <div className="responsiveness1-path-12">
                        <div className="responsiveness1-0-1-1-0-0">
                            <div className="responsiveness1-size-5">SIZE</div>
                        </div>
                        <div className="responsiveness1-0-1-1-0-1">
                            <div className="responsiveness1-0-1-1-0-1-0">
                                <div className="responsiveness1-0-1-1-0-1-0-0">
                                    <div className="responsiveness1-path-17" /> 
                                </div>
                            </div>
                            <div className="responsiveness1-0-1-1-0-1-1">
                                <div className="responsiveness1-0-1-1-0-1-1-0">
                                    <div className="responsiveness1-fixed_width-1">
                                        Fixed width
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="responsiveness1-0-1-1-0-2">
                            <div className="responsiveness1-0-1-1-0-2-0">
                                <div className="responsiveness1-0-1-1-0-2-0-0">
                                    <div className="responsiveness1-path-9" /> 
                                </div>
                            </div>
                            <div className="responsiveness1-0-1-1-0-2-1">
                                <div className="responsiveness1-0-1-1-0-2-1-0">
                                    <div className="responsiveness1-fixed_height-1">
                                        Fixed height
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="responsiveness1-0-1-2">
                    <div className="responsiveness1-path-16">
                        <div className="responsiveness1-0-1-2-0-0">
                            <div className="responsiveness1-other_options-1">
                                OTHER OPTIONS
                            </div>
                        </div>
                        <div className="responsiveness1-0-1-2-0-1">
                            <div className="responsiveness1-0-1-2-0-1-0">
                                <div className="responsiveness1-0-1-2-0-1-0-0">
                                    <div className="responsiveness1-path-2" /> 
                                </div>
                            </div>
                            <div className="responsiveness1-0-1-2-0-1-1">
                                <div className="responsiveness1-0-1-2-0-1-1-0">
                                    <div className="responsiveness1-scroll_independently-1">
                                        Scroll independently
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="responsiveness1-0-1-2-0-2">
                            <div className="responsiveness1-0-1-2-0-2-0">
                                <div className="responsiveness1-0-1-2-0-2-0-0">
                                    <div className="responsiveness1-path-75" /> 
                                </div>
                            </div>
                            <div className="responsiveness1-0-1-2-0-2-1">
                                <div className="responsiveness1-0-1-2-0-2-1-0">
                                    <div className="responsiveness1-full_window_height-2">
                                        Full window height
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="responsiveness1-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
