// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './rightbar.css';


function render() {
    return <div className="rightbar">
        { (this.props.rightMode === "code-right-bar2") ?
            <div className="rightbar-code-right-bar2">
                <div className="rightbar-0-0-0">
                    <div className="rightbar-path-7">
                        <div className="rightbar-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5156107252586247-1531117408126-4D5D592F-4D37-4EC6-902B-A240B52D85AB.png" className="rightbar-shape-5" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-1">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1344526533709461-1531117408124-F9F1E1D0-6790-43A0-BD02-A63CB7E294E2.png" onClick={this.props.addEvent} className="rightbar-path_3" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-2">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1430730508881654-1531117408122-407EAEF2-C9E3-41EE-BF03-541F23557229.png" onClick={this.props.addRepeat} className="rightbar-repeat-1" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-3">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4212325812360471-1531117408121-9966A2F0-120F-4E3D-9A3E-DD1E68C39DD2.png" onClick={this.props.addConditional} className="rightbar-optional-4" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-4">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1693520391585721-1531117408119-E3A7C373-EF28-4C22-A5E9-4A360B05E023.png" onClick={this.props.addLink} className="rightbar-link_round-_1" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-5">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1602772237566906-1531117408109-43E66350-FF19-493D-8E25-AACE06691214.png" onClick={this.props.addCursor} className="rightbar-shape-1" /> 
                        </div>
                        <div className="rightbar-0-0-0-0-6" /> 
                    </div>
                    <div className="rightbar-0-0-0-1">
                        <div className="rightbar-0-0-0-1-0">
                            <div className="rightbar-path-140">
                                <div className="rightbar-0-0-0-1-0-0-0">
                                    <div className="rightbar-path-6">
                                        <div className="rightbar-0-0-0-1-0-0-0-0-0">
                                            <div className="rightbar-component_vladmir-1">
                                                COMPONENT MAIN
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-0-0-0-1">
                                                <div className="rightbar-0-0-0-1-0-0-0-0-0-1-0">
                                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1777970413627352-1531117408107-02B45A4C-2104-4AB8-96D7-16E6B3E7F8D2.png" className="rightbar-path_9" /> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-1">
                                    { this.props.showBindings ?
                                        <div className="rightbar-path-9">
                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-0">
                                                <div className="rightbar-data_binding-7">DATA BINDING</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-1">
                                                <div className="rightbar-path-2">
                                                    <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0">
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-0">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-0-0">
                                                                <div className="rightbar-cursor-4">cursor</div>
                                                            </div>
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-1-0">
                                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1780537952921176-1531117408105-9CCD2127-92AA-4266-836F-4F85F90C35B3.png" className="rightbar-path_9-1" /> 
                                                            </div>
                                                        </div>
                                                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1035224361907042-1531117408104-9F3E992A-37DD-475A-BB11-2738E5C33241.png" className="rightbar-line-1" /> 
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-3">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-1-0-0-3-0">
                                                                <div className="rightbar-this_props_cursor-2">
                                                                    this.props.cursor
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-2">
                                                <div className="rightbar-path-3">
                                                    <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0">
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-0">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-0-0">
                                                                <div className="rightbar-font_size-5">font size</div>
                                                            </div>
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-1-0">
                                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9538462193669594-1531117408102-9ADCF7C0-B7F7-4E81-ABD2-E8084EFA2DED.png" className="rightbar-path_9-9" /> 
                                                            </div>
                                                        </div>
                                                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1457941107773510-1531117408100-C4A48AE3-E1D5-4A30-84AE-33BE986FF0B6.png" className="rightbar-line-14" /> 
                                                        <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-3">
                                                            <div className="rightbar-0-0-0-1-0-0-1-0-0-2-0-0-3-0">
                                                                <div className="rightbar-this_props_handlecli-5">
                                                                    this.props.handleClick
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-2">
                                    { this.props.showEvents ?
                                        <div className="rightbar-path-5">
                                            <div className="rightbar-0-0-0-1-0-0-2-0-0-0">
                                                <div className="rightbar-events-1">EVENTS</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-2-0-0-1">
                                                <div className="rightbar-path-4">
                                                    <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0">
                                                        <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-0">
                                                            <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-0-0">
                                                                <div className="rightbar-onclick-5">onClick</div>
                                                            </div>
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-1-0">
                                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7328840426795609-1531117408099-BEE4DBA9-B5D2-4A6B-94AD-5A7423FF941E.png" className="rightbar-path_9-7" /> 
                                                            </div>
                                                        </div>
                                                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4791391225559826-1531117408097-78D2A57E-FE3E-423C-BBB5-04230211FAA5.png" className="rightbar-line-4" /> 
                                                        <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-3">
                                                            <div className="rightbar-0-0-0-1-0-0-2-0-0-1-0-0-3-0">
                                                                <div className="rightbar-this_props_handlecli-7">
                                                                    this.props.handleClick
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-3">
                                    { this.props.showRepeat ?
                                        <div className="rightbar-path-15">
                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-0">
                                                <div className="rightbar-repeat-3">REPEAT</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-1">
                                                <div className="rightbar-path-8">
                                                    <div className="rightbar-0-0-0-1-0-0-3-0-0-1-0-0">
                                                        <div className="rightbar-this_props_list-4">
                                                            this.props.list
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-3-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-1-0-0-1-0">
                                                                <div className="rightbar-list-1">LIST</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-2">
                                                <div className="rightbar-path-1">
                                                    <div className="rightbar-0-0-0-1-0-0-3-0-0-2-0-0">
                                                        <div className="rightbar-elem-1">elem</div>
                                                        <div className="rightbar-0-0-0-1-0-0-3-0-0-2-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-2-0-0-1-0">
                                                                <div className="rightbar-instance_var-1">INSTANCE VAR</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-3">
                                                <div className="rightbar-path-79">
                                                    <div className="rightbar-0-0-0-1-0-0-3-0-0-3-0-0">
                                                        <div className="rightbar-i-5">i</div>
                                                        <div className="rightbar-0-0-0-1-0-0-3-0-0-3-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-3-0-0-1-0">
                                                                <div className="rightbar-react_key-1">REACT KEY</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-4">
                                                <div className="rightbar-path-17">
                                                    <div className="rightbar-0-0-0-1-0-0-3-0-0-4-0-0">
                                                        <div className="rightbar-8">8px</div>
                                                        <div className="rightbar-0-0-0-1-0-0-3-0-0-4-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-3-0-0-4-0-0-1-0">
                                                                <div className="rightbar-space_between-1">
                                                                    SPACE BETWEEN
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-4">
                                    { this.props.showConditional ?
                                        <div className="rightbar-path-14">
                                            <div className="rightbar-0-0-0-1-0-0-4-0-0-0">
                                                <div className="rightbar-conditional-3">CONDITIONAL</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-4-0-0-1">
                                                <div className="rightbar-path-88">
                                                    <div className="rightbar-0-0-0-1-0-0-4-0-0-1-0-0">
                                                        <div className="rightbar-this_props_show-9">
                                                            this.props.show
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-4-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-4-0-0-1-0-0-1-0">
                                                                <div className="rightbar-condition-1">CONDITION</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-4-0-0-2">
                                                <div className="rightbar-0-0-0-1-0-0-4-0-0-2-0">
                                                    <div className="rightbar-0-0-0-1-0-0-4-0-0-2-0-0">
                                                        <div className="rightbar-path-172" /> 
                                                    </div>
                                                </div>
                                                <div className="rightbar-0-0-0-1-0-0-4-0-0-2-1">
                                                    <div className="rightbar-0-0-0-1-0-0-4-0-0-2-1-0">
                                                        <div className="rightbar-occupies_space_if_hi-5">
                                                            Occupies space if hidden
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-5">
                                    { this.props.showLink ?
                                        <div className="rightbar-path-11">
                                            <div className="rightbar-0-0-0-1-0-0-5-0-0-0">
                                                <div className="rightbar-link-4">LINK</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-5-0-0-1">
                                                <div className="rightbar-path-29">
                                                    <div className="rightbar-0-0-0-1-0-0-5-0-0-1-0-0">
                                                        <div className="rightbar-https_pagedraw_io-7">
                                                            {"https://pagedraw.io"}
                                                        </div>
                                                        <div className="rightbar-0-0-0-1-0-0-5-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-5-0-0-1-0-0-1-0">
                                                                <div className="rightbar-url-1">URL</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-5-0-0-2">
                                                <div className="rightbar-0-0-0-1-0-0-5-0-0-2-0">
                                                    <div className="rightbar-0-0-0-1-0-0-5-0-0-2-0-0">
                                                        <div className="rightbar-path-59" /> 
                                                    </div>
                                                </div>
                                                <div className="rightbar-0-0-0-1-0-0-5-0-0-2-1">
                                                    <div className="rightbar-0-0-0-1-0-0-5-0-0-2-1-0">
                                                        <div className="rightbar-open_in_new_tab-5">
                                                            Open in new tab
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-6">
                                    { this.props.showCursor ?
                                        <div className="rightbar-path-49">
                                            <div className="rightbar-0-0-0-1-0-0-6-0-0-0">
                                                <div className="rightbar-cursor-1">CURSOR</div>
                                            </div>
                                            <div className="rightbar-0-0-0-1-0-0-6-0-0-1">
                                                <div className="rightbar-path-90">
                                                    <div className="rightbar-0-0-0-1-0-0-6-0-0-1-0-0">
                                                        <div className="rightbar-pointer-1">pointer</div>
                                                        <div className="rightbar-0-0-0-1-0-0-6-0-0-1-0-0-1">
                                                            <div className="rightbar-0-0-0-1-0-0-6-0-0-1-0-0-1-0">
                                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8394959037765710-1531117407921-0AF866A4-3242-4AB9-8843-0CC9E268E067.png" className="rightbar-path_9-8" /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    : null}
                                </div>
                                <div className="rightbar-0-0-0-1-0-0-7" /> 
                                <div className="rightbar-0-0-0-1-0-0-8">
                                    <div className="rightbar-path-93">
                                        <div className="rightbar-0-0-0-1-0-0-8-0-0">
                                            <div className="rightbar-external_code_integr-8">
                                                EXTERNAL CODE INTEGRATION
                                            </div>
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1594887504319042-1531117407920-D66055FB-0C78-4D35-80F8-98ABDBA01EA9.png" className="rightbar-plus-1" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.rightMode === "code-right-bar1") ?
            <div className="rightbar-code-right-bar1">
                <div className="rightbar-1-0-0">
                    <div className="rightbar-path-112">
                        <div className="rightbar-1-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1240516153160932-1531117408497-3E1F27F3-4E6C-47A2-9B89-3DC714541BC6.png" onClick={this.props.addBinding} className="rightbar-shape-12" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-1">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1098466127815577-1531117408495-3DE2A648-A61E-4F28-8D81-A79D9DD3CE80.png" onClick={this.props.addEvent} className="rightbar-path_3-1" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-2">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1320310522558943-1531117408440-20646210-D7C0-49FE-BB9D-A6085C746D29.png" onClick={this.props.addRepeat} className="rightbar-repeat-13" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-3">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2342189562463604-1531117408146-EF261987-211B-494F-8973-15348B57143F.png" onClick={this.props.addConditional} className="rightbar-optional-2" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-4">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1207316584853007-1531117408144-64402D2A-053E-4856-99AE-0F3B38050BC2.png" onClick={this.props.addLink} className="rightbar-link_round-_11" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-5">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1258393873516607-1531117408143-7FE390ED-5B37-46CE-809F-7A04F3D80BE8.png" onClick={this.props.addCursor} className="rightbar-shape-125" /> 
                        </div>
                        <div className="rightbar-1-0-0-0-6" /> 
                    </div>
                    <div className="rightbar-path-27">
                        <div className="rightbar-1-0-0-1-0">
                            <div className="rightbar-path-151">
                                <div className="rightbar-1-0-0-1-0-0-0">
                                    <div className="rightbar-component_vladmir-2">
                                        COMPONENT MAIN
                                    </div>
                                    <div className="rightbar-1-0-0-1-0-0-0-1">
                                        <div className="rightbar-1-0-0-1-0-0-0-1-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1783789869959221-1531117408141-1B474DD0-97B8-49C0-B733-CDE84F3FEB8C.png" className="rightbar-path_9-17" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-1">
                            <div className="rightbar-path-178">
                                <div className="rightbar-1-0-0-1-1-0-0">
                                    <div className="rightbar-data_binding-4">DATA BINDING</div>
                                </div>
                                <div className="rightbar-1-0-0-1-1-0-1">
                                    <div className="rightbar-1-0-0-1-1-0-1-0">
                                        <div className="rightbar-1-0-0-1-1-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-1-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-1">
                                                    Click on a element and after on     to make its properties dynamic
                                                </div>
                                                <img src="https://ucarecdn.com/b933e84d-7d0d-432d-80a5-2911cd2db07d/" className="rightbar-image-8" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-2">
                            <div className="rightbar-path-18">
                                <div className="rightbar-1-0-0-1-2-0-0">
                                    <div className="rightbar-events-11">EVENTS</div>
                                </div>
                                <div className="rightbar-1-0-0-1-2-0-1">
                                    <div className="rightbar-1-0-0-1-2-0-1-0">
                                        <div className="rightbar-1-0-0-1-2-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-2-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-12">
                                                    Click on a element and after on      to put an event on it
                                                </div>
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3213563709865869-1531117408138-335900FB-D7A2-4FA5-92CF-7284A4844D78.png" className="rightbar-path_3-3" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-3">
                            <div className="rightbar-path-48">
                                <div className="rightbar-1-0-0-1-3-0-0">
                                    <div className="rightbar-repeat-14">REPEAT</div>
                                </div>
                                <div className="rightbar-1-0-0-1-3-0-1">
                                    <div className="rightbar-1-0-0-1-3-0-1-0">
                                        <div className="rightbar-1-0-0-1-3-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-3-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-14">
                                                    Click on a element and after on      to make it repeat
                                                </div>
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1344872549949721-1531117408135-26FA3A48-7E76-446E-B4AA-85E20CD9A8F3.png" className="rightbar-repeat-134" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-4">
                            <div className="rightbar-path-496">
                                <div className="rightbar-1-0-0-1-4-0-0">
                                    <div className="rightbar-conditional-32">CONDITIONAL</div>
                                </div>
                                <div className="rightbar-1-0-0-1-4-0-1">
                                    <div className="rightbar-1-0-0-1-4-0-1-0">
                                        <div className="rightbar-1-0-0-1-4-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-4-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-2">
                                                    Click on a element and after on      to make it conditional
                                                </div>
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1092849308574504-1531117408133-E5C9AF6C-5900-450C-AA89-F7EC55C60955.png" className="rightbar-optional-1" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-5">
                            <div className="rightbar-path-21">
                                <div className="rightbar-1-0-0-1-5-0-0">
                                    <div className="rightbar-link-5">LINK</div>
                                </div>
                                <div className="rightbar-1-0-0-1-5-0-1">
                                    <div className="rightbar-1-0-0-1-5-0-1-0">
                                        <div className="rightbar-1-0-0-1-5-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-5-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-11">
                                                    Click on a element and after on      to put a link on it
                                                </div>
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8602109028918177-1531117408131-6374A5E7-6B49-450F-A1E8-AF21153D3294.png" className="rightbar-link_round-_111" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-6">
                            <div className="rightbar-path-1128">
                                <div className="rightbar-1-0-0-1-6-0-0">
                                    <div className="rightbar-cursor-13">CURSOR</div>
                                </div>
                                <div className="rightbar-1-0-0-1-6-0-1">
                                    <div className="rightbar-1-0-0-1-6-0-1-0">
                                        <div className="rightbar-1-0-0-1-6-0-1-0-0">
                                            <div className="rightbar-1-0-0-1-6-0-1-0-0-0">
                                                <div className="rightbar-click_on_a_element_a-6">
                                                    Click on a element and after on      to change cursor when mouse hovers it
                                                </div>
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1351904659478440-1531117408130-BCEC61B3-60C7-4BA4-8E3F-9E512F260AC7.png" className="rightbar-shape-13" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-7">
                            <div className="rightbar-path-76">
                                <div className="rightbar-1-0-0-1-7-0-0">
                                    <div className="rightbar-external_code_integr-88">
                                        EXTERNAL CODE INTEGRATION
                                    </div>
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8767566196376593-1531117408128-485D7FCF-8088-4D02-9D20-D87EAFE5FCFC.png" className="rightbar-plus-8" /> 
                                </div>
                            </div>
                        </div>
                        <div className="rightbar-1-0-0-1-8" /> 
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
