// Generated by https://pagedraw.io/pages/10090
import React from 'react';
import './screen_size_group.css';


function render() {
    return <div className="screen_size_group" /> ;
};

export default function(props) {
    return render.apply({props: props});
}
