// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './select-input.css';


function render() {
    return <div className="select-input-select-input-3">
        <div className="select-input-0">
            <div className="select-input-path-1">
                <div className="select-input-0-0-0">
                    <div className="select-input-0-0-0-0">
                        <div className="select-input-0-0-0-0-0">
                            <div className="select-input-cursor-6">cursor</div>
                        </div>
                    </div>
                    <div className="select-input-0-0-0-1">
                        <div className="select-input-0-0-0-1-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1392641779674321-1531117409193-33CFDACC-E597-4C0A-A36C-CD4E0647C304.png" className="select-input-path_9" /> 
                        </div>
                    </div>
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1016179992486569-1531117409192-C5193128-A525-4871-BFCE-E8B184B584A2.png" className="select-input-line-1" /> 
                    <div className="select-input-0-0-0-3">
                        <div className="select-input-0-0-0-3-0">
                            <div className="select-input-this_props_cursor-9">
                                this.props.cursor
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
