// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './select.css';


function render() {
    return <div className="select-select-1">
        <div className="select-0">
            <div className="select-path-1">
                <div className="select-0-0-0">
                    <div className="select-pointer-9">pointer</div>
                    <div className="select-0-0-0-1">
                        <div className="select-0-0-0-1-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2555060819218173-1531117409194-44455529-11B4-4C08-874F-71E388C04886.png" className="select-path_9" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
