// Generated by https://pagedraw.io/pages/10201
import React from 'react';
import './test.css';


function render() {
    return <div className="test-test-2">
        <div className="test-0">
            <div className="test-rectangle_2">
                <div className="test-0-0-0">
                    <div className="test-rectangle_3">
                        <div className="test-0-0-0-0-0">
                            <div className="test-0-0-0-0-0-0">
                                <div className="test-0-0-0-0-0-0-0">
                                    <div onClick={this.props.handleClick} className="test-design-6">
                                        DESIGN
                                    </div>
                                </div>
                            </div>
                            <div className="test-divider-1" /> 
                            <div className="test-0-0-0-0-0-2">
                                <div className="test-0-0-0-0-0-2-0">
                                    <div onClick={this.props.handleClick} className="test-code-3">
                                        CODE
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="test-1">
            <div className="test-1-0" /> 
            <div className="test-rectangle-5">
                <div className="test-1-1-0">
                    <div className="test-line-0" /> 
                    <div className="test-1-1-0-1">
                        <div className="test-1-1-0-1-0">
                            <div className="test-rectangle_4">
                                <div className="test-1-1-0-1-0-0-0">
                                    <div className="test-line_3" /> 
                                    <div className="test-1-1-0-1-0-0-0-1">
                                        <div className="test-1-1-0-1-0-0-0-1-0">
                                            <div className="test-rectangle_5" /> 
                                        </div>
                                    </div>
                                    <div className="test-1-1-0-1-0-0-0-2">
                                        <div className="test-1-1-0-1-0-0-0-2-0">
                                            <div className="test-1-1-0-1-0-0-0-2-0-0">
                                                <div className="test-rectangle_5-5" /> 
                                                <div className="test-line_3-9" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="test-1-1-0-1-0-0-0-3">
                                        <div className="test-1-1-0-1-0-0-0-3-0">
                                            <div className="test-rectangle_5-2" /> 
                                        </div>
                                    </div>
                                    <div className="test-line_3-2" /> 
                                    <div className="test-1-1-0-1-0-0-0-5">
                                        <div className="test-1-1-0-1-0-0-0-5-0">
                                            <div className="test-line_4" /> 
                                        </div>
                                        <div className="test-1-1-0-1-0-0-0-5-1">
                                            <div className="test-rectangle_5-9" /> 
                                        </div>
                                    </div>
                                    <div className="test-1-1-0-1-0-0-0-6">
                                        <div className="test-1-1-0-1-0-0-0-6-0">
                                            <div className="test-1-1-0-1-0-0-0-6-0-0">
                                                <div className="test-rectangle_5-4" /> 
                                                <div className="test-line_4-3" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="test-1-1-0-1-0-0-0-7">
                                        <div className="test-1-1-0-1-0-0-0-7-0">
                                            <div className="test-rectangle_5-7" /> 
                                        </div>
                                        <div className="test-1-1-0-1-0-0-0-7-1">
                                            <div className="test-line_4-8" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="test-1-1-0-1-1">
                            <div className="test-line_2" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="test-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
