// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './text_input.css';


function render() {
    return <div className="text_input-text_input-1">
        <div className="text_input-0">
            <div className="text_input-path-6">
                <div className="text_input-0-0-0">
                    <div className="text_input-0-0-0-0">
                        <div className="text_input-this_props_cursor-1">
                            this.props.cursor
                        </div>
                        <div className="text_input-cursor-1">CURSOR</div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
