// Generated by https://pagedraw.io/pages/11227
import React from 'react';
import './topbar.css';


function render() {
    return <div className="topbar">
        { (this.props.mode === "topbar2") ?
            <div className="topbar-topbar2">
                <div className="topbar-0-0-0">
                    <div className="topbar-path-14">
                        <div className="topbar-0-0-0-0-0">
                            <div className="topbar-0-0-0-0-0-0">
                                <div className="topbar-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1345009950334207-1531117409646-D9E1FE00-C021-41CE-89E8-6F3D61582C63.png" className="topbar-menu_icon-1" /> 
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-1">
                                <div className="topbar-0-0-0-0-0-1-0">
                                    <div className="topbar-pagedraw-teste-1">
                                        Pagedraw-teste
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-2" /> 
                            <div className="topbar-0-0-0-0-0-3">
                                <div className="topbar-0-0-0-0-0-3-0">
                                    <div className="topbar-path-12">
                                        <div className="topbar-0-0-0-0-0-3-0-0-0">
                                            <div onClick={this.props.changeToDesign} className="topbar-rectangle_3">
                                                <div className="topbar-0-0-0-0-0-3-0-0-0-0-0">
                                                    <div className="topbar-0-0-0-0-0-3-0-0-0-0-0-0">
                                                        <div className="topbar-0-0-0-0-0-3-0-0-0-0-0-0-0">
                                                            <div className="topbar-design-1">Design</div>
                                                        </div>
                                                    </div>
                                                    <div className="topbar-line_8" /> 
                                                </div>
                                            </div>
                                            <div className="topbar-path-1">
                                                <div className="topbar-0-0-0-0-0-3-0-0-0-1-0">
                                                    <div className="topbar-rectangle-6" /> 
                                                    <div className="topbar-0-0-0-0-0-3-0-0-0-1-0-1">
                                                        <div className="topbar-0-0-0-0-0-3-0-0-0-1-0-1-0">
                                                            <div className="topbar-code-5">Code</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-4" /> 
                            <div className="topbar-0-0-0-0-0-5">
                                <div className="topbar-0-0-0-0-0-5-0">
                                    <div className="topbar-rectangle_9">
                                        <div className="topbar-0-0-0-0-0-5-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1453427654035668-1531117409645-E1D47FF1-A09A-4992-BA43-64FA79940D1E.png" className="topbar-code_icon-1" /> 
                                        </div>
                                        <div className="topbar-0-0-0-0-0-5-0-0-1">
                                            <div className="topbar-create_component-1">
                                                Create component
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-6" /> 
                            <div className="topbar-0-0-0-0-0-7">
                                <div className="topbar-0-0-0-0-0-7-0">
                                    <div className="topbar-rectangle_1">
                                        <div className="topbar-0-0-0-0-0-7-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1536012727456734-1531117409643-1A0D2DFD-1061-452E-AD1A-6DE09F5EEF54.png" className="topbar-responsivness_icon-1" /> 
                                        </div>
                                        <div className="topbar-0-0-0-0-0-7-0-0-1">
                                            <div className="topbar-responsiveness-1">
                                                Responsiveness
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-8" /> 
                            <div className="topbar-0-0-0-0-0-9">
                                <div className="topbar-0-0-0-0-0-9-0">
                                    <div className="topbar-rectangle_11">
                                        <div className="topbar-0-0-0-0-0-9-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1613835432865749-1531117409641-7DE49285-56BA-4F49-83E6-2BBCE50AB264.png" className="topbar-shape-1" /> 
                                        </div>
                                        <div className="topbar-0-0-0-0-0-9-0-0-1">
                                            <div className="topbar-comments-8">Comments</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-10" /> 
                            <div className="topbar-rectangle_12">
                                <div className="topbar-0-0-0-0-0-11-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1630275830978428-1531117409640-47343257-107F-42B5-AD90-E2CF1E552E4D.png" className="topbar-surface1" /> 
                                </div>
                                <div className="topbar-0-0-0-0-0-11-1">
                                    <div className="topbar-version_control-4">
                                        Version control
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-0-0-0-0-0-12" /> 
                            <div className="topbar-0-0-0-0-0-13">
                                <div className="topbar-0-0-0-0-0-13-0">
                                    <div className="topbar-rectangle_13">
                                        <div className="topbar-0-0-0-0-0-13-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1808142069301803-1531117409639-DB66F195-624D-43A9-B182-90DE17106204.png" className="topbar-shape-18" /> 
                                        </div>
                                        <div className="topbar-0-0-0-0-0-13-0-0-1">
                                            <div className="topbar-help-1">Help</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.mode === "topbar1") ?
            <div className="topbar-topbar1">
                <div className="topbar-1-0-0">
                    <div className="topbar-path-10">
                        <div className="topbar-1-0-0-0-0">
                            <div className="topbar-1-0-0-0-0-0">
                                <div className="topbar-1-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1931667145494757-1531117409655-0EB30C4B-2E7A-4347-9BDD-8809139430FB.png" className="topbar-menu_icon-19" /> 
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-1">
                                <div className="topbar-1-0-0-0-0-1-0">
                                    <div className="topbar-pagedraw-teste-11" style={{"color": this.props.color}}>
                                        Pagedraw-teste
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-2" /> 
                            <div className="topbar-1-0-0-0-0-3">
                                <div className="topbar-1-0-0-0-0-3-0">
                                    <div className="topbar-path-6">
                                        <div className="topbar-1-0-0-0-0-3-0-0-0">
                                            <div className="topbar-path-5">
                                                <div className="topbar-1-0-0-0-0-3-0-0-0-0-0">
                                                    <div className="topbar-1-0-0-0-0-3-0-0-0-0-0-0">
                                                        <div className="topbar-1-0-0-0-0-3-0-0-0-0-0-0-0">
                                                            <div className="topbar-design-3">Design</div>
                                                        </div>
                                                    </div>
                                                    <div className="topbar-rectangle-7" /> 
                                                </div>
                                            </div>
                                            <div className="topbar-line_5" /> 
                                            <div onClick={this.props.changeToCode} className="topbar-rectangle_2">
                                                <div className="topbar-1-0-0-0-0-3-0-0-0-2-0">
                                                    <div className="topbar-code-1">Code</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-4" /> 
                            <div className="topbar-1-0-0-0-0-5">
                                <div className="topbar-1-0-0-0-0-5-0">
                                    <div className="topbar-rectangle_4">
                                        <div className="topbar-1-0-0-0-0-5-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1147069086509189-1531117409652-438770BD-88AD-43E6-B7DD-81CFF83CF8BD.png" className="topbar-code_icon-11" /> 
                                        </div>
                                        <div className="topbar-1-0-0-0-0-5-0-0-1">
                                            <div className="topbar-create_component-7">
                                                Create component
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-6" /> 
                            <div className="topbar-1-0-0-0-0-7">
                                <div className="topbar-1-0-0-0-0-7-0">
                                    <div className="topbar-rectangle_5">
                                        <div className="topbar-1-0-0-0-0-7-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1345002484038681-1531117409651-29D0C47A-5E80-4FCD-B182-D381CADD8531.png" className="topbar-responsivness_icon-13" /> 
                                        </div>
                                        <div className="topbar-1-0-0-0-0-7-0-0-1">
                                            <div className="topbar-responsiveness-16">
                                                Responsiveness
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-8" /> 
                            <div className="topbar-1-0-0-0-0-9">
                                <div className="topbar-1-0-0-0-0-9-0">
                                    <div className="topbar-rectangle_6">
                                        <div className="topbar-1-0-0-0-0-9-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4903566997555363-1531117409650-EFCEEE4C-4D00-4947-888E-54A115B3B5AB.png" className="topbar-shape-4" /> 
                                        </div>
                                        <div className="topbar-1-0-0-0-0-9-0-0-1">
                                            <div className="topbar-comments-1">Comments</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-10" /> 
                            <div className="topbar-rectangle_7">
                                <div className="topbar-1-0-0-0-0-11-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1104628460459631-1531117409649-52C779C0-0888-467B-8675-0EF5E0AB1209.png" className="topbar-surface1-1" /> 
                                </div>
                                <div className="topbar-1-0-0-0-0-11-1">
                                    <div className="topbar-version_control-2">
                                        Version control
                                    </div>
                                </div>
                            </div>
                            <div className="topbar-1-0-0-0-0-12" /> 
                            <div className="topbar-1-0-0-0-0-13">
                                <div className="topbar-1-0-0-0-0-13-0">
                                    <div className="topbar-rectangle_8">
                                        <div className="topbar-1-0-0-0-0-13-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1245692215795872-1531117409648-6BC03355-41B5-4479-A053-8F5EC380DAEF.png" className="topbar-shape-12" /> 
                                        </div>
                                        <div className="topbar-1-0-0-0-0-13-0-0-1">
                                            <div className="topbar-help-5">Help</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
